name: Sync to dha-portal

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Clone Repo B
        run: |
          git clone https://x-access-token:${{ secrets.WORKFLOW }}@github.com/fayzan101/dha-portal.git

      - name: Copy Files
        run: |
          rsync -av --exclude='.git' ./ dha-portal/

      - name: Commit & Push
        run: |
          cd dha-portal
          git config user.name "sync-bot"
          git config user.email "sync-bot@example.com"
          git add .
          git commit -m "Auto sync from DB-3-FE" || echo "No changes"
          git push