export interface ProfileFormData {
  fullName?: string;
  name?: string;
  entityName?: string;
  feeScaleId?: string;
  planType?: string;
  trialPeriod?: string;
  device?: string;
  notes?: string;
  emailAddress?: string;
  password?: string;
  phoneNumber?: string;
  category?: string;
  subCategory?: string;
  phase?: string;
  zone?: string;
  khayaban?: string;
  floor?: string;
  laneStreetNumber?: string;
  zoneName?: string;
  plotNo1?: string;
  plotNo2?: string;
  plotNo3?: string;
  cardNo?: string;
  issueDate?: string;
  expiryDate?: string;
  cardStatus?: string | boolean;
  profilePicture?: File | null;
  proofOfPossession?: File | null;
  isActive?: boolean;
  idNumber?: string;
  role?: string;
  userName?: string;
  cnic?: string;
  vehicleTagId?: string;
  cnicFront?: File | null;
  vehicleNo?: string;
  vehicleNo2?: string;
  licensePlate?: string;
  qrReference?: string;
  status?: string | boolean;
  quickPick?: string;
  fromDate?: string;
  toDate?: string;
  cnicBack?: File | null;
  search?: string;
  dob?: string;
  cardDelivery?: string;
  jobType?: string;
  fatherOrHusband?: string;
  cellNumber?: string;
  policeVerification?: string;
  address?: string;
  policeVerificationFile?: File | null;
  make?: string;
  model?: string;
  color?: string;
  year?: string;
  eTagId?: string;
  eTagType?: string;
  tagStatus?: string | boolean;
  attachment?: File | null;
  cpAgentName?: string;
  syncAgentId?: string;
  serverIp?: string;
  controller?: string;
  cpType?: string;
  tagLimit?: string;
  tagIdentityFix?: string;
  addPrinter?: string;
  printType?: string;
  interCommId?: string;
  interCommPassword?: string;
  interCommName?: string;
  laneType?: string;
  type?: string;
  laneReader?: string;
  readerSno?: string;
  manufacturer?: string;
  timeOut?: string;
  bankName?: string;
  bankCode?: string;
  rfidCardNo?: string;
  userType?: string;
  cardIssueDate?: string;
  cardExpiryDate?: string;
  accountNo?: string;
  iban?: string;
  branchCode?: string;
  branch?: string;
  serviceNo?: string;
  designation?: string;
  nextOfKin?: string;
  nextOfKinNumber?: string;
  tempPassword?: string;
  businessName?: string;
  city?: string;
  contactPerson?: string;
  cellNumber1?: string;
  cellNumber2?: string;
  vendorId?: string;
  packageName?: string;
  packageId?: string;
  minCharges?: string;
  minRenewalCharges?: string;
  phaseName?: string;
  description?: string;
  empty?: string | null;
  tagId?: string;
  tagNumber?: string;
  tagType?: string;
  validFrom?: string;
  validTo?: string;
  entityType?: string;
  entityId?: string;
  relationType?: string;
  relation?: string;
  fatherHusbandName?: string;
  residentCardNo?: string;
  feeCategory?: string;
  amount?: string | number;
  taxPercentage?: string | number;
  discountPercentage?: string | number;
  halconPercentage?: string | number;
  dhaPercentage?: string | number;
  mdrPercentage?: string | number;
  fedTaxPercentage?: string | number;
  discountValidFrom?: string;
  discountValidTo?: string;
  currency?: string;
  createdBy?: string;
  lastModifiedBy?: string;
  invoiceNumber?: string;
  invoiceDate?: string;
  paymentMethod?: string;
  transactionId?: string;
  readonly [key: string]: any;
}

export interface ProfileField {
  name: keyof ProfileFormData;
  label: string;
  type: 'text' | 'email' | 'password' | 'select' | 'date' | 'file' | 'toggle' | 'radio' | 'statusSwitch';
  required?: boolean;
  readOnly?: boolean;
  placeholder?: string;
  options?: { value: string; label: string }[];
  inputWidth?: string | number;
  inputHeight?: string | number;
  fieldWidth?: string | number;
  fieldHeight?: string | number;
  colSpan?: number;
  sameCellKey?: string;
  sameCellColumns?: number;
  isHidden?: boolean;
  onChange?: (value: string | number | boolean) => void;
}
